// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecondServer.Models;

namespace SecondServer.Migrations
{
    [DbContext(typeof(ToDoContext))]
    partial class ToDoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SecondServer.Models.ToDoChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Status");

                    b.Property<DateTime>("TimeChange");

                    b.Property<long?>("ToDoItemID");

                    b.HasKey("Id");

                    b.HasIndex("ToDoItemID");

                    b.ToTable("ToDoHistory");
                });

            modelBuilder.Entity("SecondServer.Models.ToDoItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsCompleted");

                    b.Property<DateTime>("RecentUpdate");

                    b.HasKey("ID");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("RecentUpdate");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("SecondServer.Models.ToDoChange", b =>
                {
                    b.HasOne("SecondServer.Models.ToDoItem")
                        .WithMany("Changes")
                        .HasForeignKey("ToDoItemID");
                });
#pragma warning restore 612, 618
        }
    }
}
